#!/usr/bin/env ruby
# Smoke test for the ALF backend
require 'fileutils'
class FileName
  def initialize(file)
    @mod = file.sub(/\.[^.]+$/,'') # strip last extension
    @file = file
  end
  def [](ext)
    @mod + "." + ext
  end
  def to_s
    @file
  end
end
index = File.open('index.html','w')
index.puts("<h1>LLVM->ALF Examples</h1>")
ARGV.each do |file|

  f = FileName.new(file)
  print("#{f.to_s.ljust(19)}")

  compile = "llc -march=alf -alf-standalone -alf-memory-areas=0x00-0xff -o #{f['alf']} #{f}"
  unless system("#{compile} >#{f['cclog']} 2>&1")
    puts "Build failed"
    next
  end
  
  check = "sweet -i=#{f['alf']} -c"
  unless system("#{check} >#{f['checklog']} 2>&1")
    puts "Check failed"
    next
  end
  opts="-i=#{f['alf']}"
  if File.exist? f['in']
    opts << " annot=#{f['in']}"
  else
    opts << " annot=arg.in"
  end
  if File.exist? f['obs']
    opts << " outannot=#{f['obs']}"
  end
  ae = "sweet #{opts} -ae debug=trace"
  unless system("#{ae} >#{f['aelog']} 2>&1")
    puts "AE failed #{f['aelog']}"
    next
  end
  FileUtils.mv('debug_msgs.txt',f['aetrace'])
  if File.exist?(f['out'])
    puts File.readlines(f['out'])
  else
    puts File.readlines(f['aetrace'])[-1]
  end
  index.puts("<p>#{f}&nbsp;\n<a href=\"#{f['ll']}\">LLcode</a>")
  index.puts("&nbsp;<a href=\"#{f['alf']}\">ALFcode</a></p>")
end

