#!/bin/bash
# Influential variables
#
# LLVM_ALF_FLAGS        ()     [-alf-ignore-volatiles,-alf-undefined-function-stubs]

TEST_MEMORY_AREAS="0x00000-0x00100,0x100000-0x1fffff"
LLVM_ALF_FLAGS="${LLVM_ALF_FLAGS} -alf-memory-areas=${TEST_MEMORY_AREAS}"
LLVM_ALF_FLAGS="-alf-standalone ${LLVM_ALF_FLAGS}"
source expected

export LLVM_ALF_FLAGS
make clean
TOTAL=0
ERROR=0
rm -f "error.log"
if [ -z $1 ] ; then
    TESTS="*.test"
else
    TESTS="$@"
fi
for f in $TESTS ; do
    TOTAL=$((TOTAL+1))
    M="${f/.test/}"
    rm -f "${M}.alf" "${M}.log"
    make "${M}.alf" >>"${M}.log" 2>&1
    BUILD_SUCCESS=$?
    if [ ${BUILD_SUCCESS} -eq 0 ] ; then
        bash "${M}.test"
    else
        echo "*** ${M} failed to build: see ${M}.log" >&2
    fi
    if [ "$?" -eq 0  -a "${BUILD_SUCCESS}" -eq 0  ]  ; then
        echo "${M} ok"
    else
        ERROR=$((ERROR+1))
        echo "*** ${M} ***" >> error.log
        cat "${M}.log" >> error.log
    fi
done
echo "Comparing against [1] otap-llvm HEAD + sweet HEAD (Nov 14 2011)"
echo "${TOTAL} tests executed (expected: ${EXPECTED_TESTS})"
echo "${ERROR:-0} tests failed (expected: ${EXPECTED_FAILURES}) [1]"
echo "See error.log for all error reports"
if [ "${TOTAL}" -ne "${EXPECTED_TESTS}" ] ; then
    echo "*** Unexpected number of tests"
    exit 1
fi
if [ "${ERROR}" -ne ${EXPECTED_FAILURES}  ] ; then
    echo "*** Unexpected failures"
    exit 1
fi
